---
title: "Querying genes across specificity matrices"
author: "Regina H. Reynolds"
output: 
  html_document:
    code_folding: hide
    theme: paper
    highlight: kate
    df_print: paged
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}

library(DT)
library(readxl)
library(EWCE)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(stringr)
devtools::load_all(path = "/home/rreynolds/projects/MarkerGenes/")

theme_rhr <-  theme_bw(base_family = "Helvetica") + 
  theme(panel.grid.major.x = element_blank(),
        legend.position = "right",
        strip.text = element_text(size = 7),
        axis.text.x = element_text(size = 7, angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 7),
        axis.title.y = element_text(vjust = 0.6),
        axis.title = element_text(size = 10),
        panel.spacing = unit(0.1, "lines"))

knitr::opts_chunk$set(echo = T, message= F, warning = F)
```

# Datasets used
```{r, class.source = "fold-show"}

readxl::read_excel(path = "../metadata/dataset_metadata.xlsx", sheet = "Data") %>% 
  dplyr::filter(species == "human", data_type == "SI_matrix", !resource_name %in% c("AIBS2017_MTG", "Agarwal2020_SNIG", "Agarwal2020_CRTX")) %>% 
  DT::datatable(rownames = FALSE,
                options = list(scrollX = TRUE),
                class = 'white-space: nowrap')

```
- In addition, using controls from in-house snRNA-seq of anterior cingulate cortex.

# Gene look up
```{r, class.source = "fold-show"}

genes <- c("ADRA2A")

# Load specificity matrices
load("../specificity_matrices/AIBS2018_MTG.rda")
load("../specificity_matrices/Habib2017_DroNc_Human.rda")
ctd_Inhouse_controls <- readRDS("/home/rreynolds/projects/Aim2_PDsequencing_wd/results/snRNA/specificity_matrices/2020_March/ctd_Control.rds")
load("../specificity_matrices/Lake2018_FrontalCortexOnly.rda")
load("../specificity_matrices/Lake2018_VisualCortexOnly.rda")

specificity <- 
  MarkerGenes::query_gene_ctd(genes = genes,
                              ctd_AIBS2018, ctd_DRONC_human, ctd_Inhouse_controls, ctd_BlueLake2018_FrontalCortexOnly, ctd_BlueLake2018_VisualCortexOnly,
                              celltypeLevel = 1, 
                              median_included = F,
                              genelistSpecies = "human", 
                              ctdSpecies = "human") %>% 
  dplyr::mutate(Study = str_remove(Study, "ctd_"))

specificity %>% 
  DT::datatable(rownames = FALSE,
                options = list(scrollX = TRUE),
                class = 'white-space: nowrap')

```
```{r, class.source = "fold-show", fig.cap = "**Figure**: Plot of gene specificity value across RNA-seq datasets. exPFC=glutamatergic neurons from the PFC, exCA1/3=pyramidal neurons from the Hip CA region, GABA=GABAergic interneurons, exDG=granule neurons from the Hip dentate gyrus region, ASC=astrocytes, NSC=neuronal stem cells, MG=microglia, ODC=oligodendrocytes, OPC=oligodendrocyte precursor cells, NSC=neuronal stem cells, SMC=smooth muscle cells, END= endothelial cells."}
# Plot
specificity %>% 
  ggplot(aes(x = MarkerGenes::reorder_within(x = CellType, 
                                             by = Specificity, 
                                             within = Study, 
                                             fun = median, 
                                             desc = T), 
             y = Specificity)) + 
  geom_col() +
  MarkerGenes::scale_x_reordered() +
  facet_wrap(~ Study, scales = "free_x") + 
  labs(x = "CellType") +
  theme_rhr

```

